// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUPX-Ebimr5aiktf6_NVxNpHD5YcFhig',
    appId: '1:805997849973:web:24020feed55c17af28773c',
    messagingSenderId: '805997849973',
    projectId: 'final-exam-67847',
    authDomain: 'final-exam-67847.firebaseapp.com',
    storageBucket: 'final-exam-67847.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHo0G6mk15Ll9IusuWUJ7_SYr-97na0g',
    appId: '1:805997849973:android:2af62282472b174d28773c',
    messagingSenderId: '805997849973',
    projectId: 'final-exam-67847',
    storageBucket: 'final-exam-67847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUDw3ffq4XEI22BM4-9shcUoMHGruKq8',
    appId: '1:805997849973:ios:c6ee2d3c201c25ae28773c',
    messagingSenderId: '805997849973',
    projectId: 'final-exam-67847',
    storageBucket: 'final-exam-67847.appspot.com',
    iosBundleId: 'com.example.advanceFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUDw3ffq4XEI22BM4-9shcUoMHGruKq8',
    appId: '1:805997849973:ios:c6ee2d3c201c25ae28773c',
    messagingSenderId: '805997849973',
    projectId: 'final-exam-67847',
    storageBucket: 'final-exam-67847.appspot.com',
    iosBundleId: 'com.example.advanceFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUPX-Ebimr5aiktf6_NVxNpHD5YcFhig',
    appId: '1:805997849973:web:267e86e705a1ebbd28773c',
    messagingSenderId: '805997849973',
    projectId: 'final-exam-67847',
    authDomain: 'final-exam-67847.firebaseapp.com',
    storageBucket: 'final-exam-67847.appspot.com',
  );
}
